[[language]]
name = "rust"
indent = { tab-width = 2, unit = " " }

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "python"
indent = { tab-width = 2, unit = " " }
comment-token = "#"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[[language]]
name = "powershell"
scope = "source.ps1"
roots = [".git"]
file-types = ["ps1"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
